# Generated by Django 4.1 on 2024-04-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
