# Generated by Django 4.2.3 on 2024-04-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
