# Generated by Django 4.1 on 2024-05-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_remove_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_product_admin',
            field=models.BooleanField(default=False),
        ),
    ]
