# Generated by Django 4.1 on 2024-05-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_user_is_product_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_order_admin',
            field=models.BooleanField(default=False),
        ),
    ]
